local addonName, addon = ...

-- Set up all emoticons
function addon:SetupDefaultEmojis()
    local x = self:GetEmojiSizeString()

    -- DG Emojis

    self:AddSmiley(":ana:", self:TextureString(addon.M..[[DGEmojis\AnaTheHoe.blp]], x))
    self:AddSmiley(":barbie:", self:TextureString(addon.M..[[DGEmojis\BadBarbie.blp]], x))

    -- Normal Emojis

    self:AddSmiley(":angry:", self:TextureString(addon.M..[[Emojis\Angry.blp]], x))
    self:AddSmiley(":blush:", self:TextureString(addon.M..[[Emojis\Blush.blp]], x))
    self:AddSmiley(":broken_heart:", self:TextureString(addon.M..[[Emojis\BrokenHeart.blp]], x))
    self:AddSmiley(":call_me:", self:TextureString(addon.M..[[Emojis\CallMe.blp]], x))
    self:AddSmiley(":cry:", self:TextureString(addon.M..[[Emojis\Cry.blp]], x))
    self:AddSmiley(":grin:", self:TextureString(addon.M..[[Emojis\Grin.blp]], x))
    self:AddSmiley(":heart:", self:TextureString(addon.M..[[Emojis\Heart.blp]], x))
    self:AddSmiley(":heart_eyes:", self:TextureString(addon.M..[[Emojis\HeartEyes.blp]], x))
    self:AddSmiley(":joy:", self:TextureString(addon.M..[[Emojis\Joy.blp]], x))
    self:AddSmiley(":middle_finger:", self:TextureString(addon.M..[[Emojis\MiddleFinger.blp]], x))
    self:AddSmiley(":ok_hand:", self:TextureString(addon.M..[[Emojis\OkHand.blp]], x))
    self:AddSmiley(":open_mouth:", self:TextureString(addon.M..[[Emojis\OpenMouth.blp]], x))
    self:AddSmiley(":poop:", self:TextureString(addon.M..[[Emojis\Poop.blp]], x))
    self:AddSmiley(":rage:", self:TextureString(addon.M..[[Emojis\Rage.blp]], x))
    self:AddSmiley(":scream:", self:TextureString(addon.M..[[Emojis\Scream.blp]], x))
    self:AddSmiley(":scream_cat:", self:TextureString(addon.M..[[Emojis\ScreamCat.blp]], x))
    self:AddSmiley(":semi_colon:", self:TextureString(addon.M..[[Emojis\SemiColon.blp]], x))
    self:AddSmiley(":slight_frown:", self:TextureString(addon.M..[[Emojis\SlightFrown.blp]], x))
    self:AddSmiley(":smile:", self:TextureString(addon.M..[[Emojis\Smile.blp]], x))
    self:AddSmiley(":smirk:", self:TextureString(addon.M..[[Emojis\Smirk.blp]], x))
    self:AddSmiley(":sob:", self:TextureString(addon.M..[[Emojis\Sob.blp]], x))
    self:AddSmiley(":stuck_out_tongue:", self:TextureString(addon.M..[[Emojis\StuckOutTongue.blp]], x))
    self:AddSmiley(":stuck_out_tongue_closed_eyes:", self:TextureString(addon.M..[[Emojis\StuckOutTongueClosedEyes.blp]], x))
    self:AddSmiley(":sunglasses:", self:TextureString(addon.M..[[Emojis\Sunglasses.blp]], x))
    self:AddSmiley(":thinking:", self:TextureString(addon.M..[[Emojis\Thinking.blp]], x))
    self:AddSmiley(":thumbs_up:", self:TextureString(addon.M..[[Emojis\ThumbsUp.blp]], x))
    self:AddSmiley(":wink:", self:TextureString(addon.M..[[Emojis\Wink.blp]], x))
    self:AddSmiley(":zzz:", self:TextureString(addon.M..[[Emojis\ZZZ.blp]], x))

    -- Pepe Emojis
    self:AddSmiley(":peepoalliance:", self:TextureString(addon.M..[[PepeEmojis\PeepoAlliance.blp]], x))
    self:AddSmiley(":peepohorde:", self:TextureString(addon.M..[[PepeEmojis\PeepoHorde.blp]], x))
    self:AddSmiley(":pepebitcoin:", self:TextureString(addon.M..[[PepeEmojis\PepeBitcoin.blp]], x))
    self:AddSmiley(":pepepanties:", self:TextureString(addon.M..[[PepeEmojis\PepePanties.blp]], x))
    self:AddSmiley(":pepewarlock:", self:TextureString(addon.M..[[PepeEmojis\PepeWarlock.blp]], x))

    -- Discord Emojis
    self:AddSmiley(":4head:", self:TextureString(addon.M..[[DiscordEmojis\4Head.blp]], x))
    self:AddSmiley(":5head:", self:TextureString(addon.M..[[DiscordEmojis\5Head.blp]], x))
    self:AddSmiley(":ambessalove:", self:TextureString(addon.M..[[DiscordEmojis\AmbessaLove.blp]], x))
    self:AddSmiley(":andalusiancrush:", self:TextureString(addon.M..[[DiscordEmojis\AndalusianCrush.blp]], x))
    self:AddSmiley(":anele:", self:TextureString(addon.M..[[DiscordEmojis\ANELE.blp]], x))
    self:AddSmiley(":anotherrecord:", self:TextureString(addon.M..[[DiscordEmojis\AnotherRecord.blp]], x))
    self:AddSmiley(":argieb8:", self:TextureString(addon.M..[[DiscordEmojis\ArgieB8.blp]], x))
    self:AddSmiley(":arsonnosexy:", self:TextureString(addon.M..[[DiscordEmojis\ArsonNoSexy.blp]], x))
    self:AddSmiley(":asexualpride:", self:TextureString(addon.M..[[DiscordEmojis\AsexualPride.blp]], x))
    self:AddSmiley(":asianglow:", self:TextureString(addon.M..[[DiscordEmojis\AsianGlow.blp]], x))
    self:AddSmiley(":babyrage:", self:TextureString(addon.M..[[DiscordEmojis\BabyRage.blp]], x))
    self:AddSmiley(":bangboobounce:", self:TextureString(addon.M..[[DiscordEmojis\BangbooBounce.blp]], x))
    self:AddSmiley(":batchest:", self:TextureString(addon.M..[[DiscordEmojis\BatChest.blp]], x))
    self:AddSmiley(":bcwarrior:", self:TextureString(addon.M..[[DiscordEmojis\BCWarrior.blp]], x))
    self:AddSmiley(":begwan:", self:TextureString(addon.M..[[DiscordEmojis\BegWan.blp]], x))
    self:AddSmiley(":bigbrother:", self:TextureString(addon.M..[[DiscordEmojis\BigBrother.blp]], x))
    self:AddSmiley(":bigphish:", self:TextureString(addon.M..[[DiscordEmojis\BigPhish.blp]], x))
    self:AddSmiley(":bigsad:", self:TextureString(addon.M..[[DiscordEmojis\BigSad.blp]], x))
    self:AddSmiley(":bisexualpride:", self:TextureString(addon.M..[[DiscordEmojis\BisexualPride.blp]], x))
    self:AddSmiley(":blacklivesmatter:", self:TextureString(addon.M..[[DiscordEmojis\BlackLivesMatter.blp]], x))
    self:AddSmiley(":blargnaut:", self:TextureString(addon.M..[[DiscordEmojis\BlargNaut.blp]], x))
    self:AddSmiley(":bleedpurple:", self:TextureString(addon.M..[[DiscordEmojis\BleedPurple.blp]], x))
    self:AddSmiley(":bloodtrail:", self:TextureString(addon.M..[[DiscordEmojis\BloodTrail.blp]], x))
    self:AddSmiley(":bop:", self:TextureString(addon.M..[[DiscordEmojis\BOP.blp]], x))
    self:AddSmiley(":brain:", self:TextureString(addon.M..[[DiscordEmojis\Brain.blp]], x))
    self:AddSmiley(":brainslug:", self:TextureString(addon.M..[[DiscordEmojis\BrainSlug.blp]], x))
    self:AddSmiley(":bratchat:", self:TextureString(addon.M..[[DiscordEmojis\BratChat.blp]], x))
    self:AddSmiley(":brokeback:", self:TextureString(addon.M..[[DiscordEmojis\BrokeBack.blp]], x))
    self:AddSmiley(":buddhabar:", self:TextureString(addon.M..[[DiscordEmojis\BuddhaBar.blp]], x))
    self:AddSmiley(":caitlyns:", self:TextureString(addon.M..[[DiscordEmojis\Caitlyns.blp]], x))
    self:AddSmiley(":caitthinking:", self:TextureString(addon.M..[[DiscordEmojis\CaitThinking.blp]], x))
    self:AddSmiley(":carlsmile:", self:TextureString(addon.M..[[DiscordEmojis\CarlSmile.blp]], x))
    self:AddSmiley(":cheffrank:", self:TextureString(addon.M..[[DiscordEmojis\ChefFrank.blp]], x))
    self:AddSmiley(":chewyyay:", self:TextureString(addon.M..[[DiscordEmojis\ChewyYAY.blp]], x))
    self:AddSmiley(":cinheimer:", self:TextureString(addon.M..[[DiscordEmojis\Cinheimer.blp]], x))
    self:AddSmiley(":cmonbruh:", self:TextureString(addon.M..[[DiscordEmojis\CmonBruh.blp]], x))
    self:AddSmiley(":coolcat:", self:TextureString(addon.M..[[DiscordEmojis\CoolCat.blp]], x))
    self:AddSmiley(":coolstorybob:", self:TextureString(addon.M..[[DiscordEmojis\CoolStoryBob.blp]], x))
    self:AddSmiley(":copythis:", self:TextureString(addon.M..[[DiscordEmojis\CopyThis.blp]], x))
    self:AddSmiley(":corgiderp:", self:TextureString(addon.M..[[DiscordEmojis\CorgiDerp.blp]], x))
    self:AddSmiley(":crreamawk:", self:TextureString(addon.M..[[DiscordEmojis\CrreamAwk.blp]], x))
    self:AddSmiley(":crythumbsup:", self:TextureString(addon.M..[[DiscordEmojis\CryThumbsUp.blp]], x))
    self:AddSmiley(":cuckcru:", self:TextureString(addon.M..[[DiscordEmojis\CuckCru.blp]], x))
    self:AddSmiley(":curselit:", self:TextureString(addon.M..[[DiscordEmojis\CurseLit.blp]], x))
    self:AddSmiley(":d8style:", self:TextureString(addon.M..[[DiscordEmojis\D8style.blp]], x))
    self:AddSmiley(":daesupply:", self:TextureString(addon.M..[[DiscordEmojis\DAESupply.blp]], x))
    self:AddSmiley(":dansgame:", self:TextureString(addon.M..[[DiscordEmojis\DansGame.blp]], x))
    self:AddSmiley(":darkknight:", self:TextureString(addon.M..[[DiscordEmojis\DarkKnight.blp]], x))
    self:AddSmiley(":darkmode:", self:TextureString(addon.M..[[DiscordEmojis\DarkMode.blp]], x))
    self:AddSmiley(":datsheffy:", self:TextureString(addon.M..[[DiscordEmojis\DatSheffy.blp]], x))
    self:AddSmiley(":dendiface:", self:TextureString(addon.M..[[DiscordEmojis\DendiFace.blp]], x))
    self:AddSmiley(":dinodance:", self:TextureString(addon.M..[[DiscordEmojis\DinoDance.blp]], x))
    self:AddSmiley(":dogface:", self:TextureString(addon.M..[[DiscordEmojis\DogFace.blp]], x))
    self:AddSmiley(":doritoschip:", self:TextureString(addon.M..[[DiscordEmojis\DoritosChip.blp]], x))
    self:AddSmiley(":dududu:", self:TextureString(addon.M..[[DiscordEmojis\duDudu.blp]], x))
    self:AddSmiley(":dxcat:", self:TextureString(addon.M..[[DiscordEmojis\DxCat.blp]], x))
    self:AddSmiley(":earthday:", self:TextureString(addon.M..[[DiscordEmojis\EarthDay.blp]], x))
    self:AddSmiley(":ekkochest:", self:TextureString(addon.M..[[DiscordEmojis\EkkoChest.blp]], x))
    self:AddSmiley(":entropywins:", self:TextureString(addon.M..[[DiscordEmojis\EntropyWins.blp]], x))
    self:AddSmiley(":extralife:", self:TextureString(addon.M..[[DiscordEmojis\ExtraLife.blp]], x))
    self:AddSmiley(":facepalm:", self:TextureString(addon.M..[[DiscordEmojis\Facepalm.blp]], x))
    self:AddSmiley(":failfish:", self:TextureString(addon.M..[[DiscordEmojis\FailFish.blp]], x))
    self:AddSmiley(":fallcry:", self:TextureString(addon.M..[[DiscordEmojis\FallCry.blp]], x))
    self:AddSmiley(":fallhalp:", self:TextureString(addon.M..[[DiscordEmojis\FallHalp.blp]], x))
    self:AddSmiley(":fallwinning:", self:TextureString(addon.M..[[DiscordEmojis\FallWinning.blp]], x))
    self:AddSmiley(":familyman:", self:TextureString(addon.M..[[DiscordEmojis\FamilyMan.blp]], x))
    self:AddSmiley(":fbblock:", self:TextureString(addon.M..[[DiscordEmojis\FBBlock.blp]], x))
    self:AddSmiley(":fbcatch:", self:TextureString(addon.M..[[DiscordEmojis\FBCatch.blp]], x))
    self:AddSmiley(":fbchallenge:", self:TextureString(addon.M..[[DiscordEmojis\FBChallenge.blp]], x))
    self:AddSmiley(":fbpass:", self:TextureString(addon.M..[[DiscordEmojis\FBPass.blp]], x))
    self:AddSmiley(":fbpenalty:", self:TextureString(addon.M..[[DiscordEmojis\FBPenalty.blp]], x))
    self:AddSmiley(":fbrun:", self:TextureString(addon.M..[[DiscordEmojis\FBRun.blp]], x))
    self:AddSmiley(":fbspiral:", self:TextureString(addon.M..[[DiscordEmojis\FBSpiral.blp]], x))
    self:AddSmiley(":fbtouchdown:", self:TextureString(addon.M..[[DiscordEmojis\FBTouchdown.blp]], x))
    self:AddSmiley(":feelsvi:", self:TextureString(addon.M..[[DiscordEmojis\FeelsVi.blp]], x))
    self:AddSmiley(":feverfighter:", self:TextureString(addon.M..[[DiscordEmojis\FeverFighter.blp]], x))
    self:AddSmiley(":flawlessvictory:", self:TextureString(addon.M..[[DiscordEmojis\FlawlessVictory.blp]], x))
    self:AddSmiley(":football:", self:TextureString(addon.M..[[DiscordEmojis\FootBall.blp]], x))
    self:AddSmiley(":footgoal:", self:TextureString(addon.M..[[DiscordEmojis\FootGoal.blp]], x))
    self:AddSmiley(":footyellow:", self:TextureString(addon.M..[[DiscordEmojis\FootYellow.blp]], x))
    self:AddSmiley(":forsigmar:", self:TextureString(addon.M..[[DiscordEmojis\ForSigmar.blp]], x))
    self:AddSmiley(":frankerz:", self:TextureString(addon.M..[[DiscordEmojis\FrankerZ.blp]], x))
    self:AddSmiley(":freakinstinkin:", self:TextureString(addon.M..[[DiscordEmojis\FreakinStinkin.blp]], x))
    self:AddSmiley(":fungineer:", self:TextureString(addon.M..[[DiscordEmojis\FUNgineer.blp]], x))
    self:AddSmiley(":futureman:", self:TextureString(addon.M..[[DiscordEmojis\FutureMan.blp]], x))
    self:AddSmiley(":gaypride:", self:TextureString(addon.M..[[DiscordEmojis\GayPride.blp]], x))
    self:AddSmiley(":genderfluidpride:", self:TextureString(addon.M..[[DiscordEmojis\GenderFluidPride.blp]], x))
    self:AddSmiley(":getcamped:", self:TextureString(addon.M..[[DiscordEmojis\Getcamped.blp]], x))
    self:AddSmiley(":gigachad:", self:TextureString(addon.M..[[DiscordEmojis\GigaChad.blp]], x))
    self:AddSmiley(":gingerpower:", self:TextureString(addon.M..[[DiscordEmojis\GingerPower.blp]], x))
    self:AddSmiley(":giveplz:", self:TextureString(addon.M..[[DiscordEmojis\GivePLZ.blp]], x))
    self:AddSmiley(":glitchcat:", self:TextureString(addon.M..[[DiscordEmojis\GlitchCat.blp]], x))
    self:AddSmiley(":glitchlit:", self:TextureString(addon.M..[[DiscordEmojis\GlitchLit.blp]], x))
    self:AddSmiley(":glitchnrg:", self:TextureString(addon.M..[[DiscordEmojis\GlitchNRG.blp]], x))
    self:AddSmiley(":goatemotey:", self:TextureString(addon.M..[[DiscordEmojis\GoatEmotey.blp]], x))
    self:AddSmiley(":goldplz:", self:TextureString(addon.M..[[DiscordEmojis\GoldPLZ.blp]], x))
    self:AddSmiley(":gorlock:", self:TextureString(addon.M..[[DiscordEmojis\Gorlock.blp]], x))
    self:AddSmiley(":grammarking:", self:TextureString(addon.M..[[DiscordEmojis\GrammarKing.blp]], x))
    self:AddSmiley(":grasslord:", self:TextureString(addon.M..[[DiscordEmojis\GRASSLORD.blp]], x))
    self:AddSmiley(":gunrun:", self:TextureString(addon.M..[[DiscordEmojis\GunRun.blp]], x))
    self:AddSmiley(":harleywink:", self:TextureString(addon.M..[[DiscordEmojis\HarleyWink.blp]], x))
    self:AddSmiley(":harold:", self:TextureString(addon.M..[[DiscordEmojis\Harold.blp]], x))
    self:AddSmiley(":hassanchop:", self:TextureString(addon.M..[[DiscordEmojis\HassaanChop.blp]], x))
    self:AddSmiley(":heyguys:", self:TextureString(addon.M..[[DiscordEmojis\HeyGuys.blp]], x))
    self:AddSmiley(":holidaycookie:", self:TextureString(addon.M..[[DiscordEmojis\HolidayCookie.blp]], x))
    self:AddSmiley(":holidaylog:", self:TextureString(addon.M..[[DiscordEmojis\HolidayLog.blp]], x))
    self:AddSmiley(":holidaypresent:", self:TextureString(addon.M..[[DiscordEmojis\HolidayPresent.blp]], x))
    self:AddSmiley(":holidaysanta:", self:TextureString(addon.M..[[DiscordEmojis\HolidaySanta.blp]], x))
    self:AddSmiley(":holidaytree:", self:TextureString(addon.M..[[DiscordEmojis\HolidayTree.blp]], x))
    self:AddSmiley(":hotpokket:", self:TextureString(addon.M..[[DiscordEmojis\HotPokket.blp]], x))
    self:AddSmiley(":hscheers:", self:TextureString(addon.M..[[DiscordEmojis\HSCheers.blp]], x))
    self:AddSmiley(":hswp:", self:TextureString(addon.M..[[DiscordEmojis\HSWP.blp]], x))
    self:AddSmiley(":huh:", self:TextureString(addon.M..[[DiscordEmojis\Huh.blp]], x))
    self:AddSmiley(":hungrypaimon:", self:TextureString(addon.M..[[DiscordEmojis\HungryPaimon.blp]], x))
    self:AddSmiley(":imglitch:", self:TextureString(addon.M..[[DiscordEmojis\ImGlitch.blp]], x))
    self:AddSmiley(":imtyping:", self:TextureString(addon.M..[[DiscordEmojis\ImTyping.blp]], x))
    self:AddSmiley(":intersexpride:", self:TextureString(addon.M..[[DiscordEmojis\IntersexPride.blp]], x))
    self:AddSmiley(":inuyoface:", self:TextureString(addon.M..[[DiscordEmojis\InuyoFace.blp]], x))
    self:AddSmiley(":itsboshytime:", self:TextureString(addon.M..[[DiscordEmojis\ItsBoshyTime.blp]], x))
    self:AddSmiley(":jebaited:", self:TextureString(addon.M..[[DiscordEmojis\Jebaited.blp]], x))
    self:AddSmiley(":jebasted:", self:TextureString(addon.M..[[DiscordEmojis\Jebasted.blp]], x))
    self:AddSmiley(":jinxlul:", self:TextureString(addon.M..[[DiscordEmojis\JinxLUL.blp]], x))
    self:AddSmiley(":jkanstyle:", self:TextureString(addon.M..[[DiscordEmojis\JKanStyle.blp]], x))
    self:AddSmiley(":joncarnage:", self:TextureString(addon.M..[[DiscordEmojis\JonCarnage.blp]], x))
    self:AddSmiley(":kapow:", self:TextureString(addon.M..[[DiscordEmojis\KAPOW.blp]], x))
    self:AddSmiley(":kappa:", self:TextureString(addon.M..[[DiscordEmojis\Kappa.blp]], x))
    self:AddSmiley(":kappaclaus:", self:TextureString(addon.M..[[DiscordEmojis\KappaClaus.blp]], x))
    self:AddSmiley(":kappapride:", self:TextureString(addon.M..[[DiscordEmojis\KappaPride.blp]], x))
    self:AddSmiley(":kappaross:", self:TextureString(addon.M..[[DiscordEmojis\KappaRoss.blp]], x))
    self:AddSmiley(":kappawealth:", self:TextureString(addon.M..[[DiscordEmojis\KappaWealth.blp]], x))
    self:AddSmiley(":kappu:", self:TextureString(addon.M..[[DiscordEmojis\Kappu.blp]], x))
    self:AddSmiley(":keepo:", self:TextureString(addon.M..[[DiscordEmojis\Keepo.blp]], x))
    self:AddSmiley(":kekheim:", self:TextureString(addon.M..[[DiscordEmojis\KEKHeim.blp]], x))
    self:AddSmiley(":kekw:", self:TextureString(addon.M..[[DiscordEmojis\Kekw.blp]], x))
    self:AddSmiley(":kevinturtle:", self:TextureString(addon.M..[[DiscordEmojis\KevinTurtle.blp]], x))
    self:AddSmiley(":kingworldcup:", self:TextureString(addon.M..[[DiscordEmojis\KingWorldCup.blp]], x))
    self:AddSmiley(":kippa:", self:TextureString(addon.M..[[DiscordEmojis\Kippa.blp]], x))
    self:AddSmiley(":komodohype:", self:TextureString(addon.M..[[DiscordEmojis\KomodoHype.blp]], x))
    self:AddSmiley(":koncha:", self:TextureString(addon.M..[[DiscordEmojis\KonCha.blp]], x))
    self:AddSmiley(":kreygasm:", self:TextureString(addon.M..[[DiscordEmojis\Kreygasm.blp]], x))
    self:AddSmiley(":laundrybasket:", self:TextureString(addon.M..[[DiscordEmojis\LaundryBasket.blp]], x))
    self:AddSmiley(":lechonk:", self:TextureString(addon.M..[[DiscordEmojis\Lechonk.blp]], x))
    self:AddSmiley(":lesbianpride:", self:TextureString(addon.M..[[DiscordEmojis\LesbianPride.blp]], x))
    self:AddSmiley(":lionofyara:", self:TextureString(addon.M..[[DiscordEmojis\LionOfYara.blp]], x))
    self:AddSmiley(":lul:", self:TextureString(addon.M..[[DiscordEmojis\LUL.blp]], x))
    self:AddSmiley(":mau5:", self:TextureString(addon.M..[[DiscordEmojis\Mau5.blp]], x))
    self:AddSmiley(":maxlol:", self:TextureString(addon.M..[[DiscordEmojis\MaxLOL.blp]], x))
    self:AddSmiley(":mcat:", self:TextureString(addon.M..[[DiscordEmojis\Mcat.blp]], x))
    self:AddSmiley(":mcdzombiehamburglar:", self:TextureString(addon.M..[[DiscordEmojis\McDZombieHamburglar.blp]], x))
    self:AddSmiley(":meaw:", self:TextureString(addon.M..[[DiscordEmojis\Meaw.blp]], x))
    self:AddSmiley(":mecharobot:", self:TextureString(addon.M..[[DiscordEmojis\MechaRobot.blp]], x))
    self:AddSmiley(":mercywing1:", self:TextureString(addon.M..[[DiscordEmojis\MercyWing1.blp]], x))
    self:AddSmiley(":mercywing2:", self:TextureString(addon.M..[[DiscordEmojis\MercyWing2.blp]], x))
    self:AddSmiley(":mikehogu:", self:TextureString(addon.M..[[DiscordEmojis\MikeHogu.blp]], x))
    self:AddSmiley(":minglee:", self:TextureString(addon.M..[[DiscordEmojis\MingLee.blp]], x))
    self:AddSmiley(":modlove:", self:TextureString(addon.M..[[DiscordEmojis\ModLove.blp]], x))
    self:AddSmiley(":morphintime:", self:TextureString(addon.M..[[DiscordEmojis\MorphinTime.blp]], x))
    self:AddSmiley(":mrdestructoid:", self:TextureString(addon.M..[[DiscordEmojis\MrDestructoid.blp]], x))
    self:AddSmiley(":mvgame:", self:TextureString(addon.M..[[DiscordEmojis\MVGame.blp]], x))
    self:AddSmiley(":myavatar:", self:TextureString(addon.M..[[DiscordEmojis\MyAvatar.blp]], x))
    self:AddSmiley(":newrecord:", self:TextureString(addon.M..[[DiscordEmojis\NewRecord.blp]], x))
    self:AddSmiley(":nicetry:", self:TextureString(addon.M..[[DiscordEmojis\NiceTry.blp]], x))
    self:AddSmiley(":ninjagrumpy:", self:TextureString(addon.M..[[DiscordEmojis\NinjaGrumpy.blp]], x))
    self:AddSmiley(":nomnom:", self:TextureString(addon.M..[[DiscordEmojis\NomNom.blp]], x))
    self:AddSmiley(":nonbinarypride:", self:TextureString(addon.M..[[DiscordEmojis\NonbinaryPride.blp]], x))
    self:AddSmiley(":notatk:", self:TextureString(addon.M..[[DiscordEmojis\NotATK.blp]], x))
    self:AddSmiley(":notlikethis:", self:TextureString(addon.M..[[DiscordEmojis\NotLikeThis.blp]], x))
    self:AddSmiley(":ohmydog:", self:TextureString(addon.M..[[DiscordEmojis\OhMyDog.blp]], x))
    self:AddSmiley(":onehand:", self:TextureString(addon.M..[[DiscordEmojis\OneHand.blp]], x))
    self:AddSmiley(":opieop:", self:TextureString(addon.M..[[DiscordEmojis\OpieOP.blp]], x))
    self:AddSmiley(":optimizeprime:", self:TextureString(addon.M..[[DiscordEmojis\OptimizePrime.blp]], x))
    self:AddSmiley(":osfrog:", self:TextureString(addon.M..[[DiscordEmojis\OSFrog.blp]], x))
    self:AddSmiley(":panicbasket:", self:TextureString(addon.M..[[DiscordEmojis\PanicBasket.blp]], x))
    self:AddSmiley(":panicvis:", self:TextureString(addon.M..[[DiscordEmojis\PanicVis.blp]], x))
    self:AddSmiley(":pansexualpride:", self:TextureString(addon.M..[[DiscordEmojis\PansexualPride.blp]], x))
    self:AddSmiley(":partyhat:", self:TextureString(addon.M..[[DiscordEmojis\PartyHat.blp]], x))
    self:AddSmiley(":partytime:", self:TextureString(addon.M..[[DiscordEmojis\PartyTime.blp]], x))
    self:AddSmiley(":pastathat:", self:TextureString(addon.M..[[DiscordEmojis\PastaThat.blp]], x))
    self:AddSmiley(":peopleschamp:", self:TextureString(addon.M..[[DiscordEmojis\PeoplesChamp.blp]], x))
    self:AddSmiley(":permasmug:", self:TextureString(addon.M..[[DiscordEmojis\PermaSmug.blp]], x))
    self:AddSmiley(":pewpewpew:", self:TextureString(addon.M..[[DiscordEmojis\PewPewPew.blp]], x))
    self:AddSmiley(":picomause:", self:TextureString(addon.M..[[DiscordEmojis\PicoMause.blp]], x))
    self:AddSmiley(":pikaramen:", self:TextureString(addon.M..[[DiscordEmojis\PikaRamen.blp]], x))
    self:AddSmiley(":pinkmercy:", self:TextureString(addon.M..[[DiscordEmojis\PinkMercy.blp]], x))
    self:AddSmiley(":pipehype:", self:TextureString(addon.M..[[DiscordEmojis\PipeHype.blp]], x))
    self:AddSmiley(":pixelbob:", self:TextureString(addon.M..[[DiscordEmojis\PixelBob.blp]], x))
    self:AddSmiley(":pizzatime:", self:TextureString(addon.M..[[DiscordEmojis\PizzaTime.blp]], x))
    self:AddSmiley(":pjsalt:", self:TextureString(addon.M..[[DiscordEmojis\PJSalt.blp]], x))
    self:AddSmiley(":pjsugar:", self:TextureString(addon.M..[[DiscordEmojis\PJSugar.blp]], x))
    self:AddSmiley(":pmstwin:", self:TextureString(addon.M..[[DiscordEmojis\PMSTwin.blp]], x))
    self:AddSmiley(":pog:", self:TextureString(addon.M..[[DiscordEmojis\Pog.blp]], x))
    self:AddSmiley(":pogbones:", self:TextureString(addon.M..[[DiscordEmojis\PogBones.blp]], x))
    self:AddSmiley(":pogchamp:", self:TextureString(addon.M..[[DiscordEmojis\PogChamp.blp]], x))
    self:AddSmiley(":pogging:", self:TextureString(addon.M..[[DiscordEmojis\Pogging.blp]], x))
    self:AddSmiley(":poooound:", self:TextureString(addon.M..[[DiscordEmojis\Poooound.blp]], x))
    self:AddSmiley(":popcorn:", self:TextureString(addon.M..[[DiscordEmojis\PopCorn.blp]], x))
    self:AddSmiley(":popghost:", self:TextureString(addon.M..[[DiscordEmojis\PopGhost.blp]], x))
    self:AddSmiley(":popnemo:", self:TextureString(addon.M..[[DiscordEmojis\PopNemo.blp]], x))
    self:AddSmiley(":porosad:", self:TextureString(addon.M..[[DiscordEmojis\PoroSad.blp]], x))
    self:AddSmiley(":potfriend:", self:TextureString(addon.M..[[DiscordEmojis\PotFriend.blp]], x))
    self:AddSmiley(":powerupl:", self:TextureString(addon.M..[[DiscordEmojis\PowerUpL.blp]], x))
    self:AddSmiley(":powerupr:", self:TextureString(addon.M..[[DiscordEmojis\PowerUpR.blp]], x))
    self:AddSmiley(":praiseit:", self:TextureString(addon.M..[[DiscordEmojis\PraiseIt.blp]], x))
    self:AddSmiley(":prchase:", self:TextureString(addon.M..[[DiscordEmojis\PRChase.blp]], x))
    self:AddSmiley(":primeme:", self:TextureString(addon.M..[[DiscordEmojis\PrimeMe.blp]], x))
    self:AddSmiley(":punchtrees:", self:TextureString(addon.M..[[DiscordEmojis\PunchTrees.blp]], x))
    self:AddSmiley(":punoko:", self:TextureString(addon.M..[[DiscordEmojis\PunOko.blp]], x))
    self:AddSmiley(":raccattack:", self:TextureString(addon.M..[[DiscordEmojis\RaccAttack.blp]], x))
    self:AddSmiley(":ralpherz:", self:TextureString(addon.M..[[DiscordEmojis\RalpherZ.blp]], x))
    self:AddSmiley(":redcoat:", self:TextureString(addon.M..[[DiscordEmojis\RedCoat.blp]], x))
    self:AddSmiley(":residentsleeper:", self:TextureString(addon.M..[[DiscordEmojis\ResidentSleeper.blp]], x))
    self:AddSmiley(":ripepperonis:", self:TextureString(addon.M..[[DiscordEmojis\RiPepperonis.blp]], x))
    self:AddSmiley(":ritzmitz:", self:TextureString(addon.M..[[DiscordEmojis\RitzMitz.blp]], x))
    self:AddSmiley(":rlytho:", self:TextureString(addon.M..[[DiscordEmojis\RlyTho.blp]], x))
    self:AddSmiley(":rulefive:", self:TextureString(addon.M..[[DiscordEmojis\RuleFive.blp]], x))
    self:AddSmiley(":ryuchamp:", self:TextureString(addon.M..[[DiscordEmojis\RyuChamp.blp]], x))
    self:AddSmiley(":sadkitty:", self:TextureString(addon.M..[[DiscordEmojis\SadKitty.blp]], x))
    self:AddSmiley(":sabaping:", self:TextureString(addon.M..[[DiscordEmojis\SabaPing.blp]], x))
    self:AddSmiley(":seemsgood:", self:TextureString(addon.M..[[DiscordEmojis\SeemsGood.blp]], x))
    self:AddSmiley(":serioussloth:", self:TextureString(addon.M..[[DiscordEmojis\SeriousSloth.blp]], x))
    self:AddSmiley(":shadylulu:", self:TextureString(addon.M..[[DiscordEmojis\ShadyLulu.blp]], x))
    self:AddSmiley(":shazbotstrix:", self:TextureString(addon.M..[[DiscordEmojis\ShazBotstrix.blp]], x))
    self:AddSmiley(":shocked:", self:TextureString(addon.M..[[DiscordEmojis\Shocked.blp]], x))
    self:AddSmiley(":shush:", self:TextureString(addon.M..[[DiscordEmojis\Shush.blp]], x))
    self:AddSmiley(":singsmic:", self:TextureString(addon.M..[[DiscordEmojis\SingsMic.blp]], x))
    self:AddSmiley(":singsnote:", self:TextureString(addon.M..[[DiscordEmojis\SingsNote.blp]], x))
    self:AddSmiley(":smoocherz:", self:TextureString(addon.M..[[DiscordEmojis\SmoocherZ.blp]], x))
    self:AddSmiley(":smorc:", self:TextureString(addon.M..[[DiscordEmojis\SMOrc.blp]], x))
    self:AddSmiley(":sobayed:", self:TextureString(addon.M..[[DiscordEmojis\SoBayed.blp]], x))
    self:AddSmiley(":soonerlater:", self:TextureString(addon.M..[[DiscordEmojis\SoonerLater.blp]], x))
    self:AddSmiley(":squid1:", self:TextureString(addon.M..[[DiscordEmojis\Squid1.blp]], x))
    self:AddSmiley(":squid2:", self:TextureString(addon.M..[[DiscordEmojis\Squid2.blp]], x))
    self:AddSmiley(":squid3:", self:TextureString(addon.M..[[DiscordEmojis\Squid3.blp]], x))
    self:AddSmiley(":squid4:", self:TextureString(addon.M..[[DiscordEmojis\Squid4.blp]], x))
    self:AddSmiley(":ssssss:", self:TextureString(addon.M..[[DiscordEmojis\SSSsss.blp]], x))
    self:AddSmiley(":stinkycheese:", self:TextureString(addon.M..[[DiscordEmojis\StinkyCheese.blp]], x))
    self:AddSmiley(":stinkyglitch:", self:TextureString(addon.M..[[DiscordEmojis\StinkyGlitch.blp]], x))
    self:AddSmiley(":stonelightning:", self:TextureString(addon.M..[[DiscordEmojis\StoneLightning.blp]], x))
    self:AddSmiley(":strawbeary:", self:TextureString(addon.M..[[DiscordEmojis\StrawBeary.blp]], x))
    self:AddSmiley(":subprise:", self:TextureString(addon.M..[[DiscordEmojis\SUBprise.blp]], x))
    self:AddSmiley(":subtember:", self:TextureString(addon.M..[[DiscordEmojis\SUBtember.blp]], x))
    self:AddSmiley(":supervinlin:", self:TextureString(addon.M..[[DiscordEmojis\SuperVinlin.blp]], x))
    self:AddSmiley(":swiftrage:", self:TextureString(addon.M..[[DiscordEmojis\SwiftRage.blp]], x))
    self:AddSmiley(":takenrg:", self:TextureString(addon.M..[[DiscordEmojis\TakeNRG.blp]], x))
    self:AddSmiley(":tbangel:", self:TextureString(addon.M..[[DiscordEmojis\TBAngel.blp]], x))
    self:AddSmiley(":tearglove:", self:TextureString(addon.M..[[DiscordEmojis\TearGlove.blp]], x))
    self:AddSmiley(":tehepelo:", self:TextureString(addon.M..[[DiscordEmojis\TehePelo.blp]], x))
    self:AddSmiley(":tf2john:", self:TextureString(addon.M..[[DiscordEmojis\TF2John.blp]], x))
    self:AddSmiley(":thankegg:", self:TextureString(addon.M..[[DiscordEmojis\ThankEgg.blp]], x))
    self:AddSmiley(":theilluminati:", self:TextureString(addon.M..[[DiscordEmojis\TheIlluminati.blp]], x))
    self:AddSmiley(":theringer:", self:TextureString(addon.M..[[DiscordEmojis\TheRinger.blp]], x))
    self:AddSmiley(":thetarfu:", self:TextureString(addon.M..[[DiscordEmojis\TheTarFu.blp]], x))
    self:AddSmiley(":thething:", self:TextureString(addon.M..[[DiscordEmojis\TheThing.blp]], x))
    self:AddSmiley(":thonkers:", self:TextureString(addon.M..[[DiscordEmojis\Thonkers.blp]], x))
    self:AddSmiley(":thunbeast:", self:TextureString(addon.M..[[DiscordEmojis\ThunBeast.blp]], x))
    self:AddSmiley(":tinyface:", self:TextureString(addon.M..[[DiscordEmojis\TinyFace.blp]], x))
    self:AddSmiley(":tombraid:", self:TextureString(addon.M..[[DiscordEmojis\TombRaid.blp]], x))
    self:AddSmiley(":toospicy:", self:TextureString(addon.M..[[DiscordEmojis\TooSpicy.blp]], x))
    self:AddSmiley(":tpcrunchyroll:", self:TextureString(addon.M..[[DiscordEmojis\TPcrunchyroll.blp]], x))
    self:AddSmiley(":tpfufun:", self:TextureString(addon.M..[[DiscordEmojis\TPFufun.blp]], x))
    self:AddSmiley(":transgenderpride:", self:TextureString(addon.M..[[DiscordEmojis\TransgenderPride.blp]], x))
    self:AddSmiley(":trihard:", self:TextureString(addon.M..[[DiscordEmojis\TriHard.blp]], x))
    self:AddSmiley(":troll:", self:TextureString(addon.M..[[DiscordEmojis\Troll.blp]], x))
    self:AddSmiley(":ttours:", self:TextureString(addon.M..[[DiscordEmojis\TTours.blp]], x))
    self:AddSmiley(":twitchconhype:", self:TextureString(addon.M..[[DiscordEmojis\TwitchConHYPE.blp]], x))
    self:AddSmiley(":twitchlit:", self:TextureString(addon.M..[[DiscordEmojis\TwitchLit.blp]], x))
    self:AddSmiley(":twitchraid:", self:TextureString(addon.M..[[DiscordEmojis\TwitchRaid.blp]], x))
    self:AddSmiley(":twitchrpg:", self:TextureString(addon.M..[[DiscordEmojis\TwitchRPG.blp]], x))
    self:AddSmiley(":twitchsings:", self:TextureString(addon.M..[[DiscordEmojis\TwitchSings.blp]], x))
    self:AddSmiley(":twitchunity:", self:TextureString(addon.M..[[DiscordEmojis\TwitchUnity.blp]], x))
    self:AddSmiley(":twitchvotes:", self:TextureString(addon.M..[[DiscordEmojis\TwitchVotes.blp]], x))
    self:AddSmiley(":twith:", self:TextureString(addon.M..[[DiscordEmojis\TWITH.blp]], x))
    self:AddSmiley(":unclenox:", self:TextureString(addon.M..[[DiscordEmojis\UncleNox.blp]], x))
    self:AddSmiley(":unsane:", self:TextureString(addon.M..[[DiscordEmojis\UnSane.blp]], x))
    self:AddSmiley(":uwot:", self:TextureString(addon.M..[[DiscordEmojis\UWot.blp]], x))
    self:AddSmiley(":virtualhug:", self:TextureString(addon.M..[[DiscordEmojis\VirtualHug.blp]], x))
    self:AddSmiley(":vohiyo:", self:TextureString(addon.M..[[DiscordEmojis\VoHiYo.blp]], x))
    self:AddSmiley(":votenay:", self:TextureString(addon.M..[[DiscordEmojis\VoteNay.blp]], x))
    self:AddSmiley(":voteyea:", self:TextureString(addon.M..[[DiscordEmojis\VoteYea.blp]], x))
    self:AddSmiley(":wedidthat:", self:TextureString(addon.M..[[DiscordEmojis\WeDidThat.blp]], x))
    self:AddSmiley(":wholewheat:", self:TextureString(addon.M..[[DiscordEmojis\WholeWheat.blp]], x))
    self:AddSmiley(":whysoserious:", self:TextureString(addon.M..[[DiscordEmojis\WhySoSerious.blp]], x))
    self:AddSmiley(":wtruck:", self:TextureString(addon.M..[[DiscordEmojis\WTRuck.blp]], x))
    self:AddSmiley(":wutface:", self:TextureString(addon.M..[[DiscordEmojis\WutFace.blp]], x))
    self:AddSmiley(":youdontsay:", self:TextureString(addon.M..[[DiscordEmojis\YouDontSay.blp]], x))
    self:AddSmiley(":youwhy:", self:TextureString(addon.M..[[DiscordEmojis\YouWHY.blp]], x))
    self:AddSmiley(":zlansup:", self:TextureString(addon.M..[[DiscordEmojis\ZLANsup.blp]], x))

    -- Warcraft Emojis
    self:AddSmiley(":alliance:", self:TextureString(addon.M..[[WoWEmojis\Alliance.blp]], x))
    self:AddSmiley(":disenchant:", self:TextureString(addon.M..[[WoWEmojis\Disenchant.blp]], x))
    self:AddSmiley(":druid:", self:TextureString(addon.M..[[WoWEmojis\Druid.blp]], x))
    self:AddSmiley(":feelshordeman:", self:TextureString(addon.M..[[WoWEmojis\FeelsHordeMan.blp]], x))
    self:AddSmiley(":femaledwarf:", self:TextureString(addon.M..[[WoWEmojis\FemaleDwarf.blp]], x))
    self:AddSmiley(":femalegnome:", self:TextureString(addon.M..[[WoWEmojis\FemaleGnome.blp]], x))
    self:AddSmiley(":femalehuman:", self:TextureString(addon.M..[[WoWEmojis\FemaleHuman.blp]], x))
    self:AddSmiley(":femalenightelf:", self:TextureString(addon.M..[[WoWEmojis\FemaleNightelf.blp]], x))
    self:AddSmiley(":femaleorc:", self:TextureString(addon.M..[[WoWEmojis\FemaleOrc.blp]], x))
    self:AddSmiley(":femaletauren:", self:TextureString(addon.M..[[WoWEmojis\FemaleTauren.blp]], x))
    self:AddSmiley(":femaletroll:", self:TextureString(addon.M..[[WoWEmojis\FemaleTroll.blp]], x))
    self:AddSmiley(":femaleundead:", self:TextureString(addon.M..[[WoWEmojis\FemaleUndead.blp]], x))
    self:AddSmiley(":gryphon:", self:TextureString(addon.M..[[WoWEmojis\Gryphon.blp]], x))
    self:AddSmiley(":hogger:", self:TextureString(addon.M..[[WoWEmojis\Hogger.blp]], x))
    self:AddSmiley(":horde:", self:TextureString(addon.M..[[WoWEmojis\Horde.blp]], x))
    self:AddSmiley(":hunter:", self:TextureString(addon.M..[[WoWEmojis\Hunter.blp]], x))
    self:AddSmiley(":kekdwarf:", self:TextureString(addon.M..[[WoWEmojis\KekDwarf.blp]], x))
    self:AddSmiley(":mage:", self:TextureString(addon.M..[[WoWEmojis\Mage.blp]], x))
    self:AddSmiley(":maledwarf:", self:TextureString(addon.M..[[WoWEmojis\MaleDwarf.blp]], x))
    self:AddSmiley(":malegnome:", self:TextureString(addon.M..[[WoWEmojis\MaleGnome.blp]], x))
    self:AddSmiley(":malehuman:", self:TextureString(addon.M..[[WoWEmojis\MaleHuman.blp]], x))
    self:AddSmiley(":malenightelf:", self:TextureString(addon.M..[[WoWEmojis\MaleNightelf.blp]], x))
    self:AddSmiley(":malenightelf2:", self:TextureString(addon.M..[[WoWEmojis\MaleNightelf2.blp]], x))
    self:AddSmiley(":maleorc:", self:TextureString(addon.M..[[WoWEmojis\MaleOrc.blp]], x))
    self:AddSmiley(":maletauren:", self:TextureString(addon.M..[[WoWEmojis\MaleTauren.blp]], x))
    self:AddSmiley(":maletroll:", self:TextureString(addon.M..[[WoWEmojis\MaleTroll.blp]], x))
    self:AddSmiley(":maleundead:", self:TextureString(addon.M..[[WoWEmojis\MaleUndead.blp]], x))
    self:AddSmiley(":metzen:", self:TextureString(addon.M..[[WoWEmojis\Metzen.blp]], x))
    self:AddSmiley(":moonkin:", self:TextureString(addon.M..[[WoWEmojis\Moonkin.blp]], x))
    self:AddSmiley(":murloc:", self:TextureString(addon.M..[[WoWEmojis\Murloc.blp]], x))
    self:AddSmiley(":omegawow:", self:TextureString(addon.M..[[WoWEmojis\Omegawow.blp]], x))
    self:AddSmiley(":paladin:", self:TextureString(addon.M..[[WoWEmojis\Paladin.blp]], x))
    self:AddSmiley(":priest:", self:TextureString(addon.M..[[WoWEmojis\Priest.blp]], x))
    self:AddSmiley(":rogue:", self:TextureString(addon.M..[[WoWEmojis\Rogue.blp]], x))
    self:AddSmiley(":samwise:", self:TextureString(addon.M..[[WoWEmojis\Samwise.blp]], x))
    self:AddSmiley(":shaman:", self:TextureString(addon.M..[[WoWEmojis\Shaman.blp]], x))
    self:AddSmiley(":teldrachad:", self:TextureString(addon.M..[[WoWEmojis\TeldraChad.blp]], x))
    self:AddSmiley(":uwutuskarr:", self:TextureString(addon.M..[[WoWEmojis\UwuTuskarr.blp]], x))
    self:AddSmiley(":warcraft:", self:TextureString(addon.M..[[WoWEmojis\Warcraft.blp]], x))
    self:AddSmiley(":warlock:", self:TextureString(addon.M..[[WoWEmojis\Warlock.blp]], x))
    self:AddSmiley(":warrior:", self:TextureString(addon.M..[[WoWEmojis\Warrior.blp]], x))

    -- Epoch Emojis
    self:AddSmiley(":epog:", self:TextureString(addon.M..[[EpochEmojis\Epog.blp]], x))

    -- Gnome Emojis
    self:AddSmiley(":gnomebatman:", self:TextureString(addon.M..[[GnomeEmojis\GnomeBatman.blp]], x))
    self:AddSmiley(":gnomebender:", self:TextureString(addon.M..[[GnomeEmojis\GnomeBender.blp]], x))
    self:AddSmiley(":gnomecandle:", self:TextureString(addon.M..[[GnomeEmojis\GnomeCandle.blp]], x))
    self:AddSmiley(":gnomecandleman:", self:TextureString(addon.M..[[GnomeEmojis\GnomeCandleman.blp]], x))
    self:AddSmiley(":gnomechad:", self:TextureString(addon.M..[[GnomeEmojis\GnomeChad.blp]], x))
    self:AddSmiley(":gnomeclown:", self:TextureString(addon.M..[[GnomeEmojis\GnomeClown.blp]], x))
    self:AddSmiley(":gnomedevil:", self:TextureString(addon.M..[[GnomeEmojis\GnomeDevil.blp]], x))
    self:AddSmiley(":gnomedracula:", self:TextureString(addon.M..[[GnomeEmojis\GnomeDracula.blp]], x))
    self:AddSmiley(":gnomedragonborn:", self:TextureString(addon.M..[[GnomeEmojis\GnomeDragonborn.blp]], x))
    self:AddSmiley(":gnomedruid:", self:TextureString(addon.M..[[GnomeEmojis\GnomeDruid.blp]], x))
    self:AddSmiley(":gnomeexistential:", self:TextureString(addon.M..[[GnomeEmojis\GnomeExistential.blp]], x))
    self:AddSmiley(":gnomeexoticmonk:", self:TextureString(addon.M..[[GnomeEmojis\GnomeExoticMonk.blp]], x))
    self:AddSmiley(":gnomefelguard:", self:TextureString(addon.M..[[GnomeEmojis\GnomeFelguard.blp]], x))
    self:AddSmiley(":gnomeforsaken:", self:TextureString(addon.M..[[GnomeEmojis\GnomeForsaken.blp]], x))
    self:AddSmiley(":gnomegarithos:", self:TextureString(addon.M..[[GnomeEmojis\GnomeGarithos.blp]], x))
    self:AddSmiley(":gnomegoblin:", self:TextureString(addon.M..[[GnomeEmojis\GnomeGoblin.blp]], x))
    self:AddSmiley(":gnomegodfather:", self:TextureString(addon.M..[[GnomeEmojis\GnomeGodfather.blp]], x))
    self:AddSmiley(":gnomegon:", self:TextureString(addon.M..[[GnomeEmojis\GnomeGon.blp]], x))
    self:AddSmiley(":gnomeguts:", self:TextureString(addon.M..[[GnomeEmojis\GnomeGuts.blp]], x))
    self:AddSmiley(":gnomehoplite:", self:TextureString(addon.M..[[GnomeEmojis\GnomeHoplite.blp]], x))
    self:AddSmiley(":gnomeillidan:", self:TextureString(addon.M..[[GnomeEmojis\GnomeIllidan.blp]], x))
    self:AddSmiley(":gnomeironman:", self:TextureString(addon.M..[[GnomeEmojis\GnomeIronman.blp]], x))
    self:AddSmiley(":gnomejoker:", self:TextureString(addon.M..[[GnomeEmojis\GnomeJoker.blp]], x))
    self:AddSmiley(":gnomejudge:", self:TextureString(addon.M..[[GnomeEmojis\GnomeJudge.blp]], x))
    self:AddSmiley(":gnomekratos:", self:TextureString(addon.M..[[GnomeEmojis\GnomeKratos.blp]], x))
    self:AddSmiley(":gnomeloki:", self:TextureString(addon.M..[[GnomeEmojis\GnomeLoki.blp]], x))
    self:AddSmiley(":gnomemage:", self:TextureString(addon.M..[[GnomeEmojis\GnomeMage.blp]], x))
    self:AddSmiley(":gnomemanhattan:", self:TextureString(addon.M..[[GnomeEmojis\GnomeManhattan.blp]], x))
    self:AddSmiley(":gnomemario:", self:TextureString(addon.M..[[GnomeEmojis\GnomeMario.blp]], x))
    self:AddSmiley(":gnomemickey:", self:TextureString(addon.M..[[GnomeEmojis\GnomeMickey.blp]], x))
    self:AddSmiley(":gnomemonk:", self:TextureString(addon.M..[[GnomeEmojis\GnomeMonk.blp]], x))
    self:AddSmiley(":gnomenaga:", self:TextureString(addon.M..[[GnomeEmojis\GnomeNaga.blp]], x))
    self:AddSmiley(":gnomeninja:", self:TextureString(addon.M..[[GnomeEmojis\GnomeNinja.blp]], x))
    self:AddSmiley(":gnomeorc:", self:TextureString(addon.M..[[GnomeEmojis\GnomeOrc.blp]], x))
    self:AddSmiley(":gnomeorochimaru:", self:TextureString(addon.M..[[GnomeEmojis\GnomeOrochimaru.blp]], x))
    self:AddSmiley(":gnomeshaman:", self:TextureString(addon.M..[[GnomeEmojis\GnomeShaman.blp]], x))
    self:AddSmiley(":gnomesonic:", self:TextureString(addon.M..[[GnomeEmojis\GnomeSonic.blp]], x))
    self:AddSmiley(":gnomespace:", self:TextureString(addon.M..[[GnomeEmojis\GnomeSpace.blp]], x))
    self:AddSmiley(":gnomesquidward:", self:TextureString(addon.M..[[GnomeEmojis\GnomeSquidward.blp]], x))
    self:AddSmiley(":gnometemplar:", self:TextureString(addon.M..[[GnomeEmojis\GnomeTemplar.blp]], x))
    self:AddSmiley(":gnomethor:", self:TextureString(addon.M..[[GnomeEmojis\GnomeThor.blp]], x))
    self:AddSmiley(":gnometoji:", self:TextureString(addon.M..[[GnomeEmojis\GnomeToji.blp]], x))
    self:AddSmiley(":gnomeultramarine:", self:TextureString(addon.M..[[GnomeEmojis\GnomeUltramarine.blp]], x))
    self:AddSmiley(":gnomewitcher:", self:TextureString(addon.M..[[GnomeEmojis\GnomeWitcher.blp]], x))
    self:AddSmiley(":gnomewolverine:", self:TextureString(addon.M..[[GnomeEmojis\GnomeWolverine.blp]], x))

    -- Pony Emojis
    self:AddSmiley(":ponysylvy:", self:TextureString(addon.M..[[PonyEmojis\PonySylvy.blp]], x))
    self:AddSmiley(":ponywhitemane:", self:TextureString(addon.M..[[PonyEmojis\PonyWhitemane.blp]], x))
    self:AddSmiley(":ponygarithos:", self:TextureString(addon.M..[[PonyEmojis\PonyGarithos.blp]], x))

    -- Only add text emoticons if enabled
    if ChatEmojisDB.textEmotes then
        self:AddSmiley(">:%(", self:TextureString(addon.M..[[Emojis\Rage.blp]], x))
        self:AddSmiley(":%$", self:TextureString(addon.M..[[Emojis\Blush.blp]], x))
        self:AddSmiley("<\\3", self:TextureString(addon.M..[[Emojis\BrokenHeart.blp]], x))
        self:AddSmiley(":\'%)", self:TextureString(addon.M..[[Emojis\Joy.blp]], x))
        self:AddSmiley(";\'%)", self:TextureString(addon.M..[[Emojis\Joy.blp]], x))
        self:AddSmiley(",,!,,", self:TextureString(addon.M..[[Emojis\MiddleFinger.blp]], x))
        self:AddSmiley("D:<", self:TextureString(addon.M..[[Emojis\Rage.blp]], x))
        self:AddSmiley(":o3", self:TextureString(addon.M..[[Emojis\ScreamCat.blp]], x))
        self:AddSmiley("XP", self:TextureString(addon.M..[[Emojis\StuckOutTongueClosedEyes.blp]], x))
        self:AddSmiley("8%-%)", self:TextureString(addon.M..[[Emojis\Sunglasses.blp]], x))
        self:AddSmiley("8%)", self:TextureString(addon.M..[[Emojis\Sunglasses.blp]], x))
        self:AddSmiley(":%+1:", self:TextureString(addon.M..[[Emojis\ThumbsUp.blp]], x))
        self:AddSmiley(":;:", self:TextureString(addon.M..[[Emojis\SemiColon.blp]], x))
        self:AddSmiley(";o;", self:TextureString(addon.M..[[Emojis\Sob.blp]], x))
        self:AddSmiley(":%-@", self:TextureString(addon.M..[[Emojis\Angry.blp]], x))
        self:AddSmiley(":@", self:TextureString(addon.M..[[Emojis\Angry.blp]], x))
        self:AddSmiley(":%-%)", self:TextureString(addon.M..[[Emojis\Smile.blp]], x))
        self:AddSmiley(":%)", self:TextureString(addon.M..[[Emojis\Smile.blp]], x))
        self:AddSmiley(":D", self:TextureString(addon.M..[[Emojis\Grin.blp]], x))
        self:AddSmiley(":%-D", self:TextureString(addon.M..[[Emojis\Grin.blp]], x))
        self:AddSmiley(";%-D", self:TextureString(addon.M..[[Emojis\Grin.blp]], x))
        self:AddSmiley(";D", self:TextureString(addon.M..[[Emojis\Grin.blp]], x))
        self:AddSmiley("=D", self:TextureString(addon.M..[[Emojis\Grin.blp]], x))
        self:AddSmiley("xD", self:TextureString(addon.M..[[Emojis\Grin.blp]], x))
        self:AddSmiley("XD", self:TextureString(addon.M..[[Emojis\Grin.blp]], x))
        self:AddSmiley(":%-%(", self:TextureString(addon.M..[[Emojis\SlightFrown.blp]], x))
        self:AddSmiley(":%(", self:TextureString(addon.M..[[Emojis\SlightFrown.blp]], x))
        self:AddSmiley(":o", self:TextureString(addon.M..[[Emojis\OpenMouth.blp]], x))
        self:AddSmiley(":%-o", self:TextureString(addon.M..[[Emojis\OpenMouth.blp]], x))
        self:AddSmiley(":%-O", self:TextureString(addon.M..[[Emojis\OpenMouth.blp]], x))
        self:AddSmiley(":O", self:TextureString(addon.M..[[Emojis\OpenMouth.blp]], x))
        self:AddSmiley(":%-0", self:TextureString(addon.M..[[Emojis\OpenMouth.blp]], x))
        self:AddSmiley(":P", self:TextureString(addon.M..[[Emojis\StuckOutTongue.blp]], x))
        self:AddSmiley(":%-P", self:TextureString(addon.M..[[Emojis\StuckOutTongue.blp]], x))
        self:AddSmiley(":p", self:TextureString(addon.M..[[Emojis\StuckOutTongue.blp]], x))
        self:AddSmiley(":%-p", self:TextureString(addon.M..[[Emojis\StuckOutTongue.blp]], x))
        self:AddSmiley("=P", self:TextureString(addon.M..[[Emojis\StuckOutTongue.blp]], x))
        self:AddSmiley("=p", self:TextureString(addon.M..[[Emojis\StuckOutTongue.blp]], x))
        self:AddSmiley(";%-p", self:TextureString(addon.M..[[Emojis\StuckOutTongueClosedEyes.blp]], x))
        self:AddSmiley(";p", self:TextureString(addon.M..[[Emojis\StuckOutTongueClosedEyes.blp]], x))
        self:AddSmiley(";P", self:TextureString(addon.M..[[Emojis\StuckOutTongueClosedEyes.blp]], x))
        self:AddSmiley(";%-P", self:TextureString(addon.M..[[Emojis\StuckOutTongueClosedEyes.blp]], x))
        self:AddSmiley(";%-%)", self:TextureString(addon.M..[[Emojis\Wink.blp]], x))
        self:AddSmiley(";%)", self:TextureString(addon.M..[[Emojis\Wink.blp]], x))
        self:AddSmiley(":S", self:TextureString(addon.M..[[Emojis\Smirk.blp]], x))
        self:AddSmiley(":%-S", self:TextureString(addon.M..[[Emojis\Smirk.blp]], x))
        self:AddSmiley(":,%(", self:TextureString(addon.M..[[Emojis\Cry.blp]], x))
        self:AddSmiley(":,%-%(", self:TextureString(addon.M..[[Emojis\Cry.blp]], x))
        self:AddSmiley(":\'%(", self:TextureString(addon.M..[[Emojis\Cry.blp]], x))
        self:AddSmiley(":\'%-%(", self:TextureString(addon.M..[[Emojis\Cry.blp]], x))
        self:AddSmiley(":F", self:TextureString(addon.M..[[Emojis\MiddleFinger.blp]], x))
        self:AddSmiley("<3", self:TextureString(addon.M..[[Emojis\Heart.blp]], x))
        self:AddSmiley("</3", self:TextureString(addon.M..[[Emojis\BrokenHeart.blp]], x))
    end
end

-- Function to add emoji mappings
function addon:AddSmiley(key, texture)
    if key and (type(key) == "string") and texture then
        self.Smileys[key] = texture
    end
end

-- Function to remove emoji mappings if needed
function addon:RemoveSmiley(key)
    if key and (type(key) == "string") then
        self.Smileys[key] = nil
    end
end

-- Update emoji mappings with current size
function addon:UpdateEmojiMappings()
    wipe(self.Smileys)
    self:SetupDefaultEmojis()
end

-- Helper to get emoji category
function addon:GetEmojiCategory(emojiName)
    local emojiCode = ":" .. emojiName .. ":"

    local texture = self.Smileys[emojiCode]
    if not texture then
        return "Emojis"
    end

    local categoryFolder = string.match(texture, "Media\\([^\\]+)\\")

    if categoryFolder then
        return categoryFolder
    end

    return "Emojis"
end
